version: '2'

networks:
  traefik:
    external:
      name: traefik_webgateway

services:
  npm:
    image: node:13.12.0
    restart: always
    volumes:
      - ./:/var/www/vierdeman
    working_dir: /var/www/vierdeman
    command: npm run start
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=coding-crash-course-web"
      - "traefik.frontend.rule=Host:coding-crash-course.scriptcie.nl.localhost"
      - "traefik.port=8000"
      - "traefik.docker.network=traefik_webgateway"
